### ISSUE TITLE
whoami fail with unfriendly error message

### ISSUE THREAD

**Issue by strk** [sferik/t#225]
new install, no setup done:
```
[strk@cdb:/tmp] t whoami
/var/lib/gems/1.9.1/gems/t-2.7.0/lib/t/cli.rb:904:in `whoami': undefined method `[]' for nil:NilClass (NoMethodError)
        from /var/lib/gems/1.9.1/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
        from /var/lib/gems/1.9.1/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
        from /var/lib/gems/1.9.1/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
        from /var/lib/gems/1.9.1/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
        from /var/lib/gems/1.9.1/gems/t-2.7.0/bin/t:20:in `<top (required)>'
        from /usr/local/bin/t:23:in `load'
        from /usr/local/bin/t:23:in `<main>'
```

**Comment by grzegorzblaszczyk** [comment]
@strk Ruby 1.9.1 is no longer supported by t: https://github.com/sferik/t/blob/master/t.gemspec#L24
Can this ticket be closed ?

**Comment by strk** [comment]
a friendly error message could maybe say "unsupported ruby version" ?

**Comment by sferik** [comment]
Closed by https://github.com/sferik/t/pull/245.
