### ISSUE TITLE
On Ruby 2.2.0, an error with "localtime: can't modify frozen Time"

### ISSUE THREAD

**Issue by dannguyen** [sferik/t#255]
Based off of a fresh install of Ruby 2.2.0 on rbenv/Ubuntu 14.04...trying it on Ruby 2.0.0-p598 worked fine:

```sh
$ t whois ev
/home/dun/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/t-2.8.0/lib/t.rb:8:in `localtime': can't modify frozen Time (RuntimeError)
  from /home/dun/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/t-2.8.0/lib/t.rb:8:in `local_time'
  from /home/dun/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/t-2.8.0/lib/t/printable.rb:30:in `ls_formatted_time'
  from /home/dun/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/t-2.8.0/lib/t/cli.rb:905:in `whois'
  from /home/dun/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
  from /home/dun/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
  from /home/dun/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
  from /home/dun/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
  from /home/dun/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/t-2.8.0/bin/t:20:in `<top (required)>'
  from /home/dun/.rbenv/versions/2.2.0/bin/t:23:in `load'
  from /home/dun/.rbenv/versions/2.2.0/bin/t:23:in `<main>'
```

**Comment by sferik** [comment]
Closed by https://github.com/sferik/t/commit/7c8b497c0951500371f1e5083b5621567a2a7466.
