### ISSUE TITLE
t stream timeline timed out

### ISSUE THREAD

**Issue by knonn** [sferik/t#285]
When I use t stream timeline, after a couple of seconds I got this time out : 
`
/var/lib/gems/2.1.0/gems/twitter-5.15.0/lib/twitter/streaming/connection.rb:16:in `initialize': Connection timed out - connect(2) for "199.16.156.48" port  (Errno::ETIMEDOUT)
	from /var/lib/gems/2.1.0/gems/twitter-5.15.0/lib/twitter/streaming/connection.rb:16:in `new'
	from /var/lib/gems/2.1.0/gems/twitter-5.15.0/lib/twitter/streaming/connection.rb:16:in `stream'
	from /var/lib/gems/2.1.0/gems/twitter-5.15.0/lib/twitter/streaming/client.rb:119:in `request'
	from /var/lib/gems/2.1.0/gems/twitter-5.15.0/lib/twitter/streaming/client.rb:92:in `user'
	from /var/lib/gems/2.1.0/gems/t-2.9.0/lib/t/stream.rb:146:in `timeline'
	from /var/lib/gems/2.1.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /var/lib/gems/2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /var/lib/gems/2.1.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /var/lib/gems/2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:115:in `invoke'
	from /var/lib/gems/2.1.0/gems/thor-0.19.1/lib/thor.rb:235:in `block in subcommand'
	from /var/lib/gems/2.1.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /var/lib/gems/2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /var/lib/gems/2.1.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /var/lib/gems/2.1.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /var/lib/gems/2.1.0/gems/t-2.9.0/bin/t:20:in `<top (required)>'
	from /usr/local/bin/t:23:in `load'
	from /usr/local/bin/t:23:in `<main>'
`

**Comment by gregseth** [comment]
I was just about to post about this issue. The timeout started to happen yesterday, everything was fine before. Here's my trace (slight version differences) on Ubuntu  14.04.3 LTS (trusty):

    /var/lib/gems/1.9.1/gems/twitter-5.15.0/lib/twitter/streaming/connection.rb:16:in `initialize': Connection timed out - connect(2) (Errno::ETIMEDOUT)
        from /var/lib/gems/1.9.1/gems/twitter-5.15.0/lib/twitter/streaming/connection.rb:16:in `new'
        from /var/lib/gems/1.9.1/gems/twitter-5.15.0/lib/twitter/streaming/connection.rb:16:in `stream'
        from /var/lib/gems/1.9.1/gems/twitter-5.15.0/lib/twitter/streaming/client.rb:119:in `request'
        from /var/lib/gems/1.9.1/gems/twitter-5.15.0/lib/twitter/streaming/client.rb:92:in `user'
        from /var/lib/gems/1.9.1/gems/t-2.9.0/lib/t/stream.rb:146:in `timeline'
        from /var/lib/gems/1.9.1/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
        from /var/lib/gems/1.9.1/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
        from /var/lib/gems/1.9.1/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
        from /var/lib/gems/1.9.1/gems/thor-0.19.1/lib/thor/invocation.rb:115:in `invoke'
        from /var/lib/gems/1.9.1/gems/thor-0.19.1/lib/thor.rb:235:in `block in subcommand'
        from /var/lib/gems/1.9.1/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
        from /var/lib/gems/1.9.1/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
        from /var/lib/gems/1.9.1/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
        from /var/lib/gems/1.9.1/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
        from /var/lib/gems/1.9.1/gems/t-2.9.0/bin/t:20:in `<top (required)>'
        from /usr/local/bin/t:23:in `load'
        from /usr/local/bin/t:23:in `<main>'

**Comment by zwarag** [comment]
/home/user/.gem/ruby/gems/twitter-5.15.0/lib/twitter/streaming/connection.rb:16:in `initialize': Connection timed out - connect(2) for "XXX.XXX.XXX.XXX" port  (Errno::ETIMEDOUT)
    ¦   from /home/user/.gem/ruby/gems/twitter-5.15.0/lib/twitter/streaming/connection.rb:16:in `new'
    ¦   from /home/user/.gem/ruby/gems/twitter-5.15.0/lib/twitter/streaming/connection.rb:16:in `stream'
    ¦   from /home/user/.gem/ruby/gems/twitter-5.15.0/lib/twitter/streaming/client.rb:119:in `request'
    ¦   from /home/user/.gem/ruby/gems/twitter-5.15.0/lib/twitter/streaming/client.rb:92:in `user'
    ¦   from /home/user/.gem/ruby/gems/t-2.9.0/lib/t/stream.rb:146:in `timeline'
    ¦   from /usr/share/gems/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
    ¦   from /usr/share/gems/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
    ¦   from /usr/share/gems/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'                                                                                                                                                                    
    ¦   from /usr/share/gems/gems/thor-0.19.1/lib/thor/invocation.rb:115:in `invoke'
    ¦   from /usr/share/gems/gems/thor-0.19.1/lib/thor.rb:235:in `block in subcommand'
    ¦   from /usr/share/gems/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
    ¦   from /usr/share/gems/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
    ¦   from /usr/share/gems/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
    ¦   from /usr/share/gems/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
    ¦   from /home/user/.gem/ruby/gems/t-2.9.0/bin/t:20:in `<top (required)>'
    ¦   from /home/user/bin/t:23:in `load'
    ¦   from /home/user/bin/t:23:in `<main>'

**Comment by agladders** [comment]
fix mentioned in this thread: [https://github.com/sferik/t/issues/286#issuecomment-153067380]

**Comment by felixhammerl** [comment]
This happens on my machine:
```
/usr/local/lib/ruby/gems/2.3.0/gems/twitter-5.15.0/lib/twitter/streaming/connection.rb:16:in `initialize': Can't assign requested address - connect(2) for "xxx.xxx.xxx.xxx" port  (Errno::EADDRNOTAVAIL)
```
Is this related to your error?

My setup:
```
> ruby -v
ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin15]
> gem -v
2.5.1
> t version
2.9.0
```

**Comment by daturkel** [comment]
This, and identical #286 and #287 can be fixed by merging https://github.com/animeavi/twitter/commit/6d08c5932d3033d5b69537730e02ac5905775410 into https://github.com/animeavi/twitter/. I'm submitting a pull request for that commit.

**Comment by desiac** [comment]
anyone had any success fixing this issue? I upgraded ruby and twitter, T was stable on stream for a while (to get it stable after upgrade i used the hard coded 443), then started to error again all the time??

ruby -v
ruby 2.2.4p230 (2015-12-16 revision 53155) [x86_64-linux-gnu]

gem -v
2.4.5.1

twitter-5.16.0

thanks


/var/lib/gems/2.2.0/gems/twitter-5.16.0/lib/twitter/streaming/connection.rb:16:in `initialize': Connection timed out - connect(2) for "199.59.148.139" port 443 (Errno::ETIMEDOUT)
        from /var/lib/gems/2.2.0/gems/twitter-5.16.0/lib/twitter/streaming/connection.rb:16:in `new'
        from /var/lib/gems/2.2.0/gems/twitter-5.16.0/lib/twitter/streaming/connection.rb:16:in `stream'
        from /var/lib/gems/2.2.0/gems/twitter-5.16.0/lib/twitter/streaming/client.rb:119:in `request'
        from /var/lib/gems/2.2.0/gems/twitter-5.16.0/lib/twitter/streaming/client.rb:92:in `user'
        from /var/lib/gems/2.2.0/gems/t-2.10.0/lib/t/stream.rb:146:in `timeline'
        from /var/lib/gems/2.2.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
        from /var/lib/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
        from /var/lib/gems/2.2.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
        from /var/lib/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:115:in `invoke'
        from /var/lib/gems/2.2.0/gems/thor-0.19.1/lib/thor.rb:235:in `block in subcommand'
        from /var/lib/gems/2.2.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
        from /var/lib/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
        from /var/lib/gems/2.2.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
        from /var/lib/gems/2.2.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
        from /var/lib/gems/2.2.0/gems/t-2.10.0/bin/t:20:in `<top (required)>'
        from /usr/local/bin/t:23:in `load'
        from /usr/local/bin/t:23:in `<main>'
