### ISSUE TITLE
Integrate "t" in a script and cron

### ISSUE THREAD

**Issue by shevabam** [sferik/t#288]
Hi,

I am doing a Python script that sends a tweet at the end. Here is a simple test : 

```python
#!/usr/bin/python

import subprocess

subprocess.call('t update "test"', shell=True)
```

Then chmod u+x on test.py and run ./test.py
It's ok, the tweet is sending well.

But, when I put this command in a cron : 

```
55 17  * * * /root/test.py
```
On /var/log/syslog, the cron runs well but I have nothing on my timeline... 
I tried with /usr/bin/python /root/test.py, same result.

I also test with in basic shell script: 

```shell
#!/bin/sh

t update "test"
```

And nothing on my TL with the cron job...

Any idea ?!

**Comment by dardo82** [comment]
Which user is running the `cron` jobs? What is it's `PATH` variable?

**Comment by shevabam** [comment]
The user running the cron is *root*
PATH : /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

**Comment by dardo82** [comment]
Try `which ruby` in the script to find out if cron can run t using ruby.
What are the permissions of the ruby interpreter executable binary?

**Comment by shevabam** [comment]
`which ruby` in the script returns `/usr/bin/ruby`

```
ls -l /usr/bin | grep ruby
lrwxrwxrwx 1 root   root          7 mai   10 23:58 ruby -> ruby2.1
-rwxr-xr-x 1 root   root       6168 août  26 23:52 ruby2.1
```

```
ruby --version
ruby 2.1.5p273 (2014-11-13) [x86_64-linux-gnu]
```

t version is 2.9.0
python version is 2.7.9

**Comment by dardo82** [comment]
Does your basic shell script works when run from an interactive shell?
What is the output of `which t`?

**Comment by shevabam** [comment]
Yes, the basic shell script works but not in a cron job.

```
which t
/usr/local/bin/t
```

**Comment by dardo82** [comment]
Have you tried some other script in a cron job that uses ruby?

**Comment by shevabam** [comment]
I tried with a simple script (test-t.rb) in Ruby : 

```
#!/usr/bin/ruby

tmp = File.new("tmp.txt", "w")
tmp.puts("Hello")
tmp.close
```

This cron job works, I have my tmp.txt file : 

```
43 15 * * * /root/test-t.rb
```

Then, I wrote a script in Python (test-rb.py) that calls this Ruby script : 

```
#!/usr/bin/python

import subprocess

subprocess.call('/root/test-t.rb', shell=True)
```

And the cron job `46 15 * * * /root/test-rb.py` works perfectly...

**Comment by dardo82** [comment]
What are the shells you and cron use?

**Comment by shevabam** [comment]
It's a fresh install of a basic Debian 8.
User = bash with `ps -p $$`

I do not have the SHELL=... entry in crontab so it's bash too ?

**Comment by dardo82** [comment]
I think that it should be the root's shell, so bash the same I suppose...

**Comment by eschultze** [comment]
I was able to do it with:
`HOME=/home/<user>/usr/local/bin/t update -P /home/<user>/.trc "New message you want to tweet"`

Replace <user> with you username.
Please also note that  `-P` must be AFTER the command.

**Comment by pxlbrnd** [comment]
Hope this helps....

I ran

```
env -i $SHELL --norc
```
to enter the shell used by cron, then searched for my twitter followers
```
bash-4.2$ t followers @pxlbrnd
```
 and got this output:
```

/var/lib/gems/1.9.1/gems/t-2.9.0/lib/t/cli.rb:34:in `expand_path': couldn't find HOME environment -- expanding `~' (ArgumentError)
	from /var/lib/gems/1.9.1/gems/t-2.9.0/lib/t/cli.rb:34:in `<class:CLI>'
	from /var/lib/gems/1.9.1/gems/t-2.9.0/lib/t/cli.rb:19:in `<module:T>'
	from /var/lib/gems/1.9.1/gems/t-2.9.0/lib/t/cli.rb:18:in `<top (required)>'
	from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
	from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
	from /var/lib/gems/1.9.1/gems/t-2.9.0/lib/t.rb:1:in `<top (required)>'
	from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
	from /usr/lib/ruby/1.9.1/rubygems/custom_require.rb:36:in `require'
	from /var/lib/gems/1.9.1/gems/t-2.9.0/bin/t:8:in `<top (required)>'
	from /usr/local/bin/t:23:in `load'
	from /usr/local/bin/t:23:in `<main>'
```

Using the same t-command in an interactive shell worked fine.

**Comment by pxlbrnd** [comment]
I managed to solve the problem for me. I inserted ```/bin/bash -l -c``` into the crontab to make it look like:
```0 0 * * 5 /bin/bash -l -c /home/pxlbrnd/foo/bar.sh```.
```bar.sh``` runs ```t```, amongst other things.

Hope this helps!

**Comment by mitchellkrogza** [comment]
Quite easy to run `t` from cron. I do it this way if it helps anyone.

Make a shell script like this.

```
#!/bin/bash
cd /home/myusername
t update "My Tweet. #tweet" -f /var/www/mywebsite/image.jpg
exit 0
```

Save the file as `/home/yourusername/tweet.sh`

Make it executable of course `chmod +x /home/yourusername/tweet.sh`

Make SURE you allow the script to run with sudo from cron by adding the script path to you username in visudo

`yourusername ALL=(ALL) NOPASSWD: /home/yourusername/tweet.sh`

Then add the cron entry as 

`00 10 * * * sudo /home/yourusername/tweet.sh` (example to run it at 10 am)
