### ISSUE TITLE
thor error

### ISSUE THREAD

**Issue by plittlefield** [sferik/t#291]
I now get this error:-

    /var/lib/gems/1.9.1/gems/thor-0.19.1/lib/thor/parser/arguments.rb:12:in `block in split': invalid byte sequence in UTF-8 (ArgumentError)
        from /var/lib/gems/1.9.1/gems/thor-0.19.1/lib/thor/parser/arguments.rb:11:in `each'
        from /var/lib/gems/1.9.1/gems/thor-0.19.1/lib/thor/parser/arguments.rb:11:in `split'
        from /var/lib/gems/1.9.1/gems/thor-0.19.1/lib/thor.rb:340:in `dispatch'
        from /var/lib/gems/1.9.1/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /var/lib/gems/1.9.1/gems/t-2.9.0/bin/t:20:in `<top (required)>'
	from /usr/local/bin/tweet:19:in `load'
	from /usr/local/bin/tweet:19:in `<main>'

$ tweet --version
2.9.0

$ gem --version
1.8.11

**Comment by plittlefield** [comment]
Ah, figured it. I have a weird character in my input.... Queensr�che

How do I clean 'Queensr�che' in PERL or BASH?

I have a PERL script that gets my XML feed from last.fm and then generates my top 3 artists.

**Comment by plittlefield** [comment]
OK, it's a fudge, but I can pipe it through the Linux command 'strings' and then remove the new line...

    /home/paully/Bin/lastfm.pl | strings | tr -d '\n'
