### ISSUE TITLE
Sample command isn't working

### ISSUE THREAD

**Issue by jasontucker** [sferik/t#295]
I'm running OS X El Cap 10.11.1 when I run one of the sample commands I get the following error:

$ t followings -l --sort=tweeted | head -10 | awk '{print $1}' | xargs t unfollow -i
/usr/local/lib/ruby/gems/2.2.0/gems/twitter-5.15.0/lib/twitter/utils.rb:39:in `value': No live threads left. Deadlock? (fatal)
	from /usr/local/lib/ruby/gems/2.2.0/gems/twitter-5.15.0/lib/twitter/utils.rb:39:in `collect'
	from /usr/local/lib/ruby/gems/2.2.0/gems/twitter-5.15.0/lib/twitter/utils.rb:39:in `pmap'
	from /usr/local/lib/ruby/gems/2.2.0/gems/twitter-5.15.0/lib/twitter/rest/utils.rb:116:in `parallel_users_from_response'
	from /usr/local/lib/ruby/gems/2.2.0/gems/twitter-5.15.0/lib/twitter/rest/friends_and_followers.rb:154:in `unfollow'
	from /usr/local/lib/ruby/gems/2.2.0/gems/t-2.9.0/lib/t/cli.rb:836:in `block in unfollow'
	from /usr/local/lib/ruby/gems/2.2.0/gems/t-2.9.0/lib/t/utils.rb:54:in `block in fetch_users'
	from /usr/local/lib/ruby/gems/2.2.0/gems/retryable-2.0.3/lib/retryable.rb:67:in `retryable'
	from /usr/local/lib/ruby/gems/2.2.0/gems/t-2.9.0/lib/t/utils.rb:53:in `fetch_users'
	from /usr/local/lib/ruby/gems/2.2.0/gems/t-2.9.0/lib/t/cli.rb:835:in `unfollow'
	from /usr/local/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
	from /usr/local/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
	from /usr/local/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
	from /usr/local/lib/ruby/gems/2.2.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
	from /usr/local/lib/ruby/gems/2.2.0/gems/t-2.9.0/bin/t:20:in `<top (required)>'
	from /usr/local/bin/t:23:in `load'
	from /usr/local/bin/t:23:in `<main>'

**Comment by innerspirit** [comment]
Been happening to me also. Only fix I found was to use -n 1 on xargs:
```$ t followings -l --sort=tweeted | head -10 | awk '{print $1}' | xargs -n 1 t unfollow -i```

You can also add -P 4 to make it run faster. Sadly, none of this works for ```t follow``` for me.

**Comment by sferik** [comment]
This deadlock was caused by the `twitter` gem's `pmap` method, which spawned threads in `parallel_users_from_response` when processing multiple users via `xargs`.

The legacy Ruby CLI has since been rewritten to use the `x` gem. The `unfollow` command now processes users sequentially via `mutate_users` (`filter_map` loop) — no threads, no deadlock.

The Rust CLI also processes users sequentially in a simple `for` loop, so this is not an issue there either.
