### ISSUE TITLE
Can not run `t authorize`, undefined method error from oauth.

### ISSUE THREAD

**Issue by AJFaraday** [sferik/t#326]
I've just run a fresh install of t on Lubuntu. 

On my first try of the t executable, to run authorize, I get this error, apparently coming from a gem spec.

```ruby
$ t authorize
/home/ajfaraday/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/specification.rb:2158:in `method_missing': undefined method `this' for #<Gem::Specification:0x61ca88 oauth-0.4.7> (NoMethodError)
        from /home/ajfaraday/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/specification.rb:1057:in `find_active_stub_by_path'
        from /home/ajfaraday/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:64:in `require'
        from /home/ajfaraday/.rvm/gems/ruby-2.3.0/gems/t-2.10.0/bin/t:7:in `<top (required)>'
        from /home/ajfaraday/.rvm/gems/ruby-2.3.0/bin/t:23:in `load'
        from /home/ajfaraday/.rvm/gems/ruby-2.3.0/bin/t:23:in `<main>'
        from /home/ajfaraday/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
        from /home/ajfaraday/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'
```

This same error is thrown in all ruby executables.

I'm using ruby 2.3.0 via rvm...

```
$ ruby -v
ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-linux]
$ gem -v
2.5.1
```

**Comment by Shwetakale** [comment]
@AJFaraday I checked it on ruby ```version 2.3.1``` and it works as expected. I didn't face any issue so I think you can now upgrade to ```ruby 2.3.1``` instead of downgrading to  ```2.2.2```

**Comment by compuguy** [comment]
Issue #402 has a work around to this.
