### ISSUE TITLE
"t stream timeline" crashes after a few moments

### ISSUE THREAD

**Issue by Hund** [sferik/t#347]
I'm running Arch Linux, Ruby 2.3.1, gem 2.6.7 and t 2.10.0. And when I run `t stream timeline` this happens after like 10-60 seconds:

```
/usr/lib/ruby/2.3.0/openssl/buffering.rb:125:in `sysread': end of file reached (EOFError)
    from /usr/lib/ruby/2.3.0/openssl/buffering.rb:125:in `readpartial'
    from /home/johan/.gem/ruby/2.3.0/gems/twitter-5.16.0/lib/twitter/streaming/connection.rb:21:in `stream'
    from /home/johan/.gem/ruby/2.3.0/gems/twitter-5.16.0/lib/twitter/streaming/client.rb:119:in `request'
    from /home/johan/.gem/ruby/2.3.0/gems/twitter-5.16.0/lib/twitter/streaming/client.rb:92:in `user'
    from /home/johan/.gem/ruby/2.3.0/gems/t-2.10.0/lib/t/stream.rb:146:in `timeline'
    from /home/johan/.gem/ruby/2.3.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
    from /home/johan/.gem/ruby/2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
    from /home/johan/.gem/ruby/2.3.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
    from /home/johan/.gem/ruby/2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:115:in `invoke'
    from /home/johan/.gem/ruby/2.3.0/gems/thor-0.19.1/lib/thor.rb:235:in `block in subcommand'
    from /home/johan/.gem/ruby/2.3.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
    from /home/johan/.gem/ruby/2.3.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
    from /home/johan/.gem/ruby/2.3.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
    from /home/johan/.gem/ruby/2.3.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
    from /home/johan/.gem/ruby/2.3.0/gems/t-2.10.0/bin/t:20:in `<top (required)>'
    from /home/johan/.gem/ruby/2.3.0/bin/t:22:in `load'
    from /home/johan/.gem/ruby/2.3.0/bin/t:22:in `<main>'
```

I have no idea what to do?

**Comment by kaffeeknecht** [comment]
Same here. 
Ubuntu 16.05.1
ruby 2.3.1p112
t 2.10.0
gem 2.5.1

```
/usr/lib/ruby/1.9.1/openssl/buffering.rb:121:in `sysread': end of file reached (EOFError)
        from /usr/lib/ruby/1.9.1/openssl/buffering.rb:121:in `readpartial'
        from /var/lib/gems/1.9.1/gems/twitter-5.16.0/lib/twitter/streaming/connection.rb:21:in `stream'
        from /var/lib/gems/1.9.1/gems/twitter-5.16.0/lib/twitter/streaming/client.rb:119:in `request'
        from /var/lib/gems/1.9.1/gems/twitter-5.16.0/lib/twitter/streaming/client.rb:92:in `user'
        from /var/lib/gems/1.9.1/gems/t-2.10.0/lib/t/stream.rb:146:in `timeline'
        from /var/lib/gems/1.9.1/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
        from /var/lib/gems/1.9.1/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
        from /var/lib/gems/1.9.1/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
        from /var/lib/gems/1.9.1/gems/thor-0.19.1/lib/thor/invocation.rb:115:in `invoke'
        from /var/lib/gems/1.9.1/gems/thor-0.19.1/lib/thor.rb:235:in `block in subcommand'
        from /var/lib/gems/1.9.1/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
        from /var/lib/gems/1.9.1/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
        from /var/lib/gems/1.9.1/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
        from /var/lib/gems/1.9.1/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
        from /var/lib/gems/1.9.1/gems/t-2.10.0/bin/t:20:in `<top (required)>'
        from /usr/local/bin/t:23:in `load'
        from /usr/local/bin/t:23:in `<main>'
```

**Comment by Hund** [comment]
I don't know how and why, but t seems to be working again? Perhaps the issue was at the Twitter service itself and not t?

**Comment by Hund** [comment]
It has been working for some time now. It's not t's fault anyway. :)
