### ISSUE TITLE
New release required

### ISSUE THREAD

**Issue by alyssais** [sferik/t#388]
b40e2088971811a83f917b22bc928ed8ee30e21b fixed a bug that prevents `t authorize` from running:

```
Traceback (most recent call last):
        7: from /Users/qyliss/.gem/ruby/2.5.0/bin/t:23:in `<main>'
        6: from /Users/qyliss/.gem/ruby/2.5.0/bin/t:23:in `load'
        5: from /Users/qyliss/.gem/ruby/2.5.0/gems/t-3.1.0/bin/t:20:in `<top (required)>'
        4: from /Users/qyliss/.gem/ruby/2.5.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
        3: from /Users/qyliss/.gem/ruby/2.5.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
        2: from /Users/qyliss/.gem/ruby/2.5.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
        1: from /Users/qyliss/.gem/ruby/2.5.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
/Users/qyliss/.gem/ruby/2.5.0/gems/t-3.1.0/lib/t/cli.rb:82:in `authorize': uninitialized constant Twitter::REST::Client::BASE_URL (NameError)
```

There should probably be a new release of the gem including b40e2088971811a83f917b22bc928ed8ee30e21b so `t authorize` isn't broken for new installs.

**Comment by lattatude** [comment]
I'm getting similar error

```
$ t authorize
...

Enter your API key: 
Enter your API secret: 
/var/lib/gems/2.3.0/gems/t-3.1.0/lib/t/cli.rb:82:in `authorize': uninitialized constant Twitter::REST::Client::BASE_URL (NameError)
	from /var/lib/gems/2.3.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /var/lib/gems/2.3.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /var/lib/gems/2.3.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	from /var/lib/gems/2.3.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	from /var/lib/gems/2.3.0/gems/t-3.1.0/bin/t:20:in `<top (required)>'
	from /usr/local/bin/t:22:in `load'
	from /usr/local/bin/t:22:in `<main>'

$ uname -a && ruby -v
Linux 4.13.0-21-generic #24-Ubuntu SMP Mon Dec 18 17:29:16 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
ruby 2.3.3p222 (2016-11-21) [x86_64-linux-gnu]
```

**Comment by ilkermutlu** [comment]
Same here

```
Enter your API key: ***
Enter your API secret: ***
/Users/ilker/.rvm/gems/ruby-2.4.1@global/gems/t-3.1.0/lib/t/cli.rb:82:in `authorize': uninitialized constant Twitter::REST::Client::BASE_URL (NameError)
        from /Users/ilker/.rvm/gems/ruby-2.4.1@global/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
        from /Users/ilker/.rvm/gems/ruby-2.4.1@global/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
        from /Users/ilker/.rvm/gems/ruby-2.4.1@global/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
        from /Users/ilker/.rvm/gems/ruby-2.4.1@global/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
        from /Users/ilker/.rvm/gems/ruby-2.4.1@global/gems/t-3.1.0/bin/t:20:in `<top (required)>'
        from /Users/ilker/.rvm/rubies/ruby-2.4.1/bin/t:23:in `load'
        from /Users/ilker/.rvm/rubies/ruby-2.4.1/bin/t:23:in `<main>'
        from /Users/ilker/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `eval'
        from /Users/ilker/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `<main>'
```

```
$ uname -a && ruby -v
Darwin mbp 17.3.0 Darwin Kernel Version 17.3.0: Thu Nov  9 18:09:22 PST 2017; root:xnu-4570.31.3~1/RELEASE_X86_64 x86_64
ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin17]
```

**Comment by DanielBarreno** [comment]
/var/lib/gems/2.3.0/gems/t-3.1.0/lib/t/cli.rb:82:in `authorize': uninitialized constant Twitter::REST::Client::BASE_URL (NameError)
        from /var/lib/gems/2.3.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
        from /var/lib/gems/2.3.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
        from /var/lib/gems/2.3.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
        from /var/lib/gems/2.3.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
        from /var/lib/gems/2.3.0/gems/t-3.1.0/bin/t:20:in `<top (required)>'
        from /usr/local/bin/t:22:in `load'
        from /usr/local/bin/t:22:in `<main>'

**Comment by jm3** [comment]
@sferik would love some help getting this fixed so i can use t again!

**Comment by dardo82** [comment]
I've had this problem too…
This one-liner should fix it.
`sed -i '' ’s/Client/Request/g' $(gem env | awk '/ - \//&&!/bin/{print $2}' | xargs -I @ find @ -type d -name t)/cli.rb`

**Comment by compuguy** [comment]
See Issue #402 and sferik/twitter#878

**Comment by hamboneZA** [comment]
> I've had this problem too…
> This one-liner should fix it.
> `sed -i '' ’s/Client/Request/g' $(gem env | awk '/ - \//&&!/bin/{print $2}' | xargs -I @ find @ -type d -name t)/cli.rb`

Just came here to say that worked a treat on OSX Big Sur @dardo82, thanks! Two years down the line it is still the gift that keeps on keeps on giving.

**Comment by dardo82** [comment]
> Just came here to say that worked a treat on OSX Big Sur @dardo82, thanks! Two years down the line it is still the gift that keeps on keeps on giving.

Merry Christmas! Enjoy the gift; best things in life are free.
