### ISSUE TITLE
Error on fresh install: `require': cannot load such file -- json

### ISSUE THREAD

**Issue by giacecco** [sferik/t#396]
Hi All,
I've used *t* before and re-installed today on a new laptop, but whatever I do I get this error. I checked the README and the GitHub issues section for dependencies or similar issues but couldn't find an answer. I'm using Fedora 27. Please help! Thanks.

```
$ t authorize
/usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- json (LoadError)
	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/giacecco/.gem/ruby/gems/http-3.0.0/lib/http/mime_type/json.rb:3:in `<top (required)>'
	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/giacecco/.gem/ruby/gems/http-3.0.0/lib/http/mime_type.rb:78:in `<top (required)>'
	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/giacecco/.gem/ruby/gems/http-3.0.0/lib/http/response.rb:7:in `<top (required)>'
	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/giacecco/.gem/ruby/gems/http-3.0.0/lib/http.rb:15:in `<top (required)>'
	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/giacecco/.gem/ruby/gems/twitter-6.2.0/lib/twitter/rest/request.rb:2:in `<top (required)>'
	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/giacecco/.gem/ruby/gems/twitter-6.2.0/lib/twitter/cursor.rb:2:in `<top (required)>'
	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/giacecco/.gem/ruby/gems/twitter-6.2.0/lib/twitter.rb:3:in `<top (required)>'
	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/giacecco/.gem/ruby/gems/t-3.1.0/lib/t/cli.rb:5:in `<top (required)>'
	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/giacecco/.gem/ruby/gems/t-3.1.0/lib/t.rb:1:in `<top (required)>'
	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/share/rubygems/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /home/giacecco/.gem/ruby/gems/t-3.1.0/bin/t:8:in `<top (required)>'
	from /home/giacecco/bin/t:23:in `load'
	from /home/giacecco/bin/t:23:in `<main>'
$ 
```

**Comment by sguzman** [comment]
I'm having this issue as well on EndeavourOS

**Comment by plum** [comment]
I ahve this problem whne tryin gto authenticate after installing hte arch linux package. I  receivied the suggstion  it may be a python 2 and python 3 compatribility problem. But I dont know, really.
