### ISSUE TITLE
`authorize': uninitialized constant Twitter::REST::Client::BASE_URL (NameError)

### ISSUE THREAD

**Issue by improvethings** [sferik/t#402]
$ t authorize
Welcome! Before you can use t, you'll first need to register an
application with Twitter. Just follow the steps below:
  1. Sign in to the Twitter Application Management site and click
     "Create New App".
  2. Complete the required fields and submit the form.
     Note: Your application must have a unique name.
  3. Go to the Permissions tab of your application, and change the
     Access setting to "Read, Write and Access direct messages".
  4. Go to the Keys and Access Tokens tab to view the consumer key
     and secret which you'll need to copy and paste below when
     prompted.

Press [Enter] to open the Twitter Developer site.

Enter your API key: <snip>
Enter your API secret: <snop>
/Library/Ruby/Gems/2.3.0/gems/t-3.1.0/lib/t/cli.rb:82:in `authorize': uninitialized constant Twitter::REST::Client::BASE_URL (NameError)
	from /Library/Ruby/Gems/2.3.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
	from /Library/Ruby/Gems/2.3.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	from /Library/Ruby/Gems/2.3.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	from /Library/Ruby/Gems/2.3.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	from /Library/Ruby/Gems/2.3.0/gems/t-3.1.0/bin/t:20:in `<top (required)>'
	from /usr/local/bin/t:22:in `load'
	from /usr/local/bin/t:22:in `<main>'

$ uname -srm
Darwin 17.5.0 x86_64
$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.13.4
$ system_profiler SPSoftwareDataType
Software:

    System Software Overview:

      System Version: macOS 10.13.4 (17E202)
      Kernel Version: Darwin 17.5.0
      Boot Volume: osx
      Boot Mode: Normal
$ t --version
3.1.0

**Comment by keekerdc** [comment]
Can reproduce here. Probably an update to the `twitter` gem?

**Comment by jpluscplusm** [comment]
Same issue here, just installed `t` system-wide on OSX 10.11.6.

```
Traceback (most recent call last):
	7: from /usr/local/bin/t:23:in `<main>'
	6: from /usr/local/bin/t:23:in `load'
	5: from /usr/local/lib/ruby/gems/2.5.0/gems/t-3.1.0/bin/t:20:in `<top (required)>'
	4: from /usr/local/lib/ruby/gems/2.5.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
	3: from /usr/local/lib/ruby/gems/2.5.0/gems/thor-0.20.0/lib/thor.rb:387:in `dispatch'
	2: from /usr/local/lib/ruby/gems/2.5.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
	1: from /usr/local/lib/ruby/gems/2.5.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
/usr/local/lib/ruby/gems/2.5.0/gems/t-3.1.0/lib/t/cli.rb:82:in `authorize': uninitialized constant Twitter::REST::Client::BASE_URL (NameError)
$ t --version
3.1.0
```

**Comment by wayne5540** [comment]
For anyone who is looking for a quick solution, you can try https://github.com/sferik/twitter/issues/878#issuecomment-392878152

**Comment by jorisvanzundert** [comment]
Had the same issue on ruby 2.5.0p0 (2017-12-25 revision 61468) [x86_64-darwin17], for me this fix  https://github.com/sferik/twitter/issues/878#issuecomment-349718252 worked by addressing the https://github.com/sferik/twitter api differently. 

I cannot however estimate if this fix would mend the problem in general and in a proper way. Hope that a better informed maintainer can judge?

**Comment by devlato** [comment]
The issue still reproduces. Any way to fix that?

**Comment by epitron** [comment]
`t` works with v6.1.0 of the twitter gem, so I fixed it by running:

```
$ gem install twitter -v 6.1.0
$ gem uninstall twitter -v 6.2.0
```

The simplest upstream fix is to change `t.gemspec`'s twitter dependency to `~> 6.1.0` instead of `~> 6.0`.

**Comment by mitchellkrogza** [comment]
Thanks @epitron your simple solution worked a treat.

**Comment by epitron** [comment]
@sferik Would you mind merging the pull request? (#412) This gem has been in a broken state for a while.

**Comment by galenfarrel** [comment]
> `t` works with v6.1.0 of the twitter gem, so I fixed it by running:
> 
> ```
> $ gem install twitter -v 6.1.0
> $ gem uninstall twitter -v 6.2.0
> ```
> 
> The simplest upstream fix is to change `t.gemspec`'s twitter dependency to `~> 6.1.0` instead of `~> 6.0`. (Submitted a pull request with this change: #412)

This fixed it for me.

**Comment by Eoin-ONeill-Yokai** [comment]
Hey, that fix works for me. It should be noted that you also need rdoc as well. That's probably obvious to people who already know ruby, but it wasn't for me. :)

**Comment by natterstefan** [comment]
@epitron's solution worked for me too. Thank you.

**Comment by jasalt** [comment]
Earlier @epitron solution works for authentication, but then dm is still not working https://github.com/sferik/t/issues/405. Updating twitter dependency to 7.0 fixes this, but with it the authentication is broken... So what I ended up doing to be able to log in and to send a dm:

First, authentication is broken after twitter gem 6.1.0 so downgrade to it after t-3.1.0 gem installation:

```
gem install twitter -v 6.1.0
gem uninstall twitter -v 6.2.0

```
Now authenticate, most things should work after that. To get dm working make sure first the app has permission for dm's (hidden under "Permissions" tab on API control panel). Then update twitter gem to 7.0.0.

Then to make DM's work change `/usr/local/lib/ruby/gems/2.7.0/gems/t-3.1.0/t.gemspec` to upgrage twitter gem to 7.0 in `/usr/local/lib/ruby/gems/2.7.0/specifications/t-3.1.0.gemspec`:

`s.add_runtime_dependency(%q<twitter>.freeze, ["~> 7.0"])`

Then install the 7.0.0 in place of 6.1.0.

```
gem install twitter -v 7.0.0
gem uninstall twitter -v 6.1.0
```

Then you should have this installed and working mostly. Additionally hide ruby `faraday` deprecation warnings as noted in https://github.com/sferik/t/issues/424#issuecomment-643549067.

**Comment by pdelteil** [comment]
> ```
> gem uninstall twitter -v 6.1.0
> ```

Thank you for your help.  In Ubuntu 20.04, the file to edit the dependencies is

` /var/lib/gems/2.7.0/specifications/t-3.1.0.gemspec
`

**Comment by dmuth** [comment]
This workaround no longer works as of Ruby 3 on OS/X:

![image](https://user-images.githubusercontent.com/374060/111042065-6b051780-8409-11eb-977a-936f6c9a7c52.png)

**Comment by k4rtik** [comment]
Use this fork instead: https://github.com/xiaocang/t

Build and install instructions:
```
gem build t.gemspec
gem install t-3.1.1.gem
```
