### ISSUE TITLE
trace back when authorising twitter

### ISSUE THREAD

**Issue by marrie** [sferik/t#417]
1. Install t
2. Type t authorize
3. Follow the prompts when trying to create the app, or if you had t prior regenarate the api and secret keys.
4. Paste the information in the terminal

This is when the trouble starts with 

	7: from /usr/local/bin/t:23:in `<main>'
	6: from /usr/local/bin/t:23:in `load'
	5: from /Library/Ruby/Gems/2.6.0/gems/t-3.1.0/bin/t:20:in `<top (required)>'
	4: from /Library/Ruby/Gems/2.6.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	3: from /Library/Ruby/Gems/2.6.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	2: from /Library/Ruby/Gems/2.6.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	1: from /Library/Ruby/Gems/2.6.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
/Library/Ruby/Gems/2.6.0/gems/t-3.1.0/lib/t/cli.rb:82:in `authorize': uninitialized constant Twitter::REST::Client::BASE_URL (NameError)
Sarahs-MacBook-Air:~ sa$ 

ProductVersion:	10.15.1
BuildVersion:	19B86a

I hope that helps a bit.

**Comment by jsmiith** [comment]
Look back through the numerous other issues about this - I'm sure you'll manage to find a solution.

**Comment by sferik** [comment]
Thank you for taking the time to report this issue.

Now that X has introduced [Pay-Per-Use API Pricing](https://x.com/i/trending/2019901839370531129), I've rewritten the `t` CLI in Rust (it has also been renamed to `x`).

If you believe this issue still applies to the new CLI, please reopen this issue or open a new one with updated details. Thank you for your understanding and your contributions to this project!
