### ISSUE TITLE
Trouble loading twitter gem

### ISSUE THREAD

**Issue by dylanmatthews** [sferik/t#429]
Hey there - first off, thanks so much to sferik for this great utility. t seems to be having some trouble connecting to the twitter gem on my machine. I'm on macOS, installing gems through homebrew. Here's what happens when I try to do a mass-unfollow on my account:

```
Dylans-MacBook-Air:gems dylanmatthews$ t followings | xargs t unfollow
Traceback (most recent call last):
	10: from /usr/local/bin/t:6:in `<main>'
	 9: from /usr/local/bin/t:6:in `load'
	 8: from /usr/local/Cellar/gem-t/3.1.0/gems/t-3.1.0/bin/t:8:in `<top (required)>'
	 7: from /usr/local/Cellar/ruby/2.7.1_2/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
	 6: from /usr/local/Cellar/ruby/2.7.1_2/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
	 5: from /usr/local/Cellar/gem-t/3.1.0/gems/t-3.1.0/lib/t.rb:1:in `<top (required)>'
	 4: from /usr/local/Cellar/ruby/2.7.1_2/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
	 3: from /usr/local/Cellar/ruby/2.7.1_2/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
	 2: from /usr/local/Cellar/gem-t/3.1.0/gems/t-3.1.0/lib/t/cli.rb:5:in `<top (required)>'
	 1: from /usr/local/Cellar/ruby/2.7.1_2/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
/usr/local/Cellar/ruby/2.7.1_2/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require': cannot load such file -- twitter (LoadError)
```
At first I thought I had forgotten to install sferik's twitter gem, but that does not seem to be the issue:

```
Dylans-MacBook-Air:gems dylanmatthews$ brew gem info t
gem-t: stable 3.1.0
/usr/local/Cellar/gem-t/3.1.0 (932 files, 10.3MB) *
  Built from source on 2020-07-31 at 12:21:14
From: /var/folders/mj/49b6bp_x0zd7m35v7h04_88r0000gn/T/gem-t.rb
==> Dependencies
Required: ruby ✔
Dylans-MacBook-Air:gems dylanmatthews$ brew gem info twitter
gem-twitter: stable 7.0.0
/usr/local/Cellar/gem-twitter/7.0.0 (1,461 files, 17MB) *
  Built from source on 2020-07-31 at 13:00:47
From: /var/folders/mj/49b6bp_x0zd7m35v7h04_88r0000gn/T/gem-twitter.rb
==> Dependencies
Required: ruby ✔
```

I might just be making a n00b error here but has anyone run into an issue like this? I tried uninstalling twitter 7.0.0 and reinstalling twitter 6.1.0, on the theory that this is an interoperability issue with the latest version of the twitter gem, but that didn't appear to do anything.

**Comment by dylanmatthews** [comment]
Uninstalling t and twitter and then reinstalling t alone fixed the issue for whatever reason; closing this. Sorry to bug!
