### ISSUE TITLE
Error after entering API Key and API Secret Key

### ISSUE THREAD

**Issue by codeinred** [sferik/t#451]
Hi everyone,

I installed the cli client and created a twitter app. I enabled read, write, and direct message permissions for the twitter app. When I try to authorize it, I get the following error message. I've provided the output below, with the keys redacted.
```Welcome! Before you can use t, you'll first need to register an
application with Twitter. Just follow the steps below:
  1. Sign in to the Twitter Application Management site and click
     "Create New App".
  2. Complete the required fields and submit the form.
     Note: Your application must have a unique name.
  3. Go to the Permissions tab of your application, and change the
     Access setting to "Read, Write and Access direct messages".
  4. Go to the Keys and Access Tokens tab to view the consumer key
     and secret which you'll need to copy and paste below when
     prompted.

Press [Enter] to open the Twitter Developer site. 

Enter your API key: [redacted]
Enter your API secret: [redacted]
/home/alecto/.local/share/gem/ruby/3.0.0/gems/t-3.1.0/lib/t/cli.rb:82:in `authorize': uninitialized constant Twitter::REST::Client::BASE_URL (NameError)
	from /home/alecto/.local/share/gem/ruby/3.0.0/gems/thor-1.1.0/lib/thor/command.rb:27:in `run'
	from /home/alecto/.local/share/gem/ruby/3.0.0/gems/thor-1.1.0/lib/thor/invocation.rb:127:in `invoke_command'
	from /home/alecto/.local/share/gem/ruby/3.0.0/gems/thor-1.1.0/lib/thor.rb:392:in `dispatch'
	from /home/alecto/.local/share/gem/ruby/3.0.0/gems/thor-1.1.0/lib/thor/base.rb:485:in `start'
	from /home/alecto/.local/share/gem/ruby/3.0.0/gems/t-3.1.0/bin/t:20:in `<top (required)>'
	from /home/alecto/.local/share/gem/ruby/3.0.0/bin/t:23:in `load'
	from /home/alecto/.local/share/gem/ruby/3.0.0/bin/t:23:in `<main>'
```

**Comment by shuuji3** [comment]
I think this is the same issue as #402.

**Comment by AntZoo** [comment]
[This solution](https://github.com/sferik/twitter/issues/878#issuecomment-401299182) works perfectly.
