### ISSUE TITLE
uninitialized constant Twitter::REST::Client::BASE_URL (NameError)

### ISSUE THREAD

**Issue by charafsalmi** [sferik/t#458]
I just performed a fresh install. There is the error I get:

```
PS C:\Users\user> t authorize
Welcome! Before you can use t, you'll first need to register an
application with Twitter. Just follow the steps below:
  1. Sign in to the Twitter Application Management site and click
     "Create New App".
  2. Complete the required fields and submit the form.
     Note: Your application must have a unique name.
  3. Go to the Permissions tab of your application, and change the
     Access setting to "Read, Write and Access direct messages".
  4. Go to the Keys and Access Tokens tab to view the consumer key
     and secret which you'll need to copy and paste below when
     prompted.

Press [Enter] to open the Twitter Developer site.
Enter your API key: HIDDEN
Enter your API secret: HIDDEN
C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/t-3.1.0/lib/t/cli.rb:82:in `authorize': uninitialized constant Twitter::REST::Client::BASE_URL (NameError)
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/thor-1.2.1/lib/thor/base.rb:485:in `start'
        from C:/Ruby30-x64/lib/ruby/gems/3.0.0/gems/t-3.1.0/bin/t:20:in `<top (required)>'
        from C:/Ruby30-x64/bin/t:25:in `load'
        from C:/Ruby30-x64/bin/t:25:in `<main>'

PS C:\Users\user> ruby --version
ruby 3.0.3p157 (2021-11-24 revision 3fb7d2cadc) [x64-mingw32]
```

I tried twice.

**Comment by Debdut** [comment]
Same. I think it doesn't work anymore!

**Comment by cllns** [comment]
Related: https://github.com/sferik/twitter/issues/878

**Comment by czhu** [comment]
follow the instruction https://github.com/sferik/twitter/issues/878#issuecomment-502450602
it works for me

**Comment by maxqxam** [comment]
Same issue here

**Comment by MrAureliusR** [comment]
Welp, this sucks. Wish I had known this was unsupported before installing it.

**Comment by daehokimm** [comment]
It will be helpful

https://github.com/sferik/twitter/issues/878#issuecomment-401299182
